name: Playwright Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Asegúrate de que esta sea la versión de Python que usas
      - name: Instalar dependencias de Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Asegúrate de que pytest-playwright esté en requirements.txt
      - name: Instalar navegadores de Playwright
        run: playwright install --with-deps
      - name: Ejecutar pruebas de Playwright en orden específico
        run: |
          # El orden de ejecución de los archivos de prueba se define aquí
          pytest test_login.py test_home.py test_producto.py test_carrito.py test_menu.py -s -v
      - name: Subir informe de pruebas de Playwright
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30